# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.utils.timezone
import otp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                            ("change_email", "Change Email"),
                            ("delete_account", "Delete Account"),
                            ("sensitive_action", "Sensitive Action"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="6-digit numeric code.", max_length=6),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, default=otp.models._default_expiry
                    ),
                ),
                ("is_used", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "db_table": "otp",
                "ordering": ["-created_at"],
            },
        ),
    ]
