# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "purpose", "is_used"], name="idx_otp_user_purpose_used"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["expires_at"], name="idx_otp_expires_at"),
        ),
    ]
