# Generated by Django 6.0.3 on 2026-03-24 09:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPalWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="PayPal webhook event ID — used for deduplication.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="e.g. PAYMENT.CAPTURE.COMPLETED", max_length=64
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. capture, subscription",
                        max_length=64,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the PayPal resource involved.",
                        max_length=64,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=15,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Full webhook payload stored for audit/replay."
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed."
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Webhook Event",
                "verbose_name_plural": "PayPal Webhook Events",
                "db_table": "paypal_webhook_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayPalOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "paypal_order_id",
                    models.CharField(
                        db_index=True,
                        help_text="The id returned by PayPal Orders API on creation.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("activation", "Plan Activation"),
                            ("upgrade", "Plan Upgrade"),
                        ],
                        default="activation",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in the order currency.",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", help_text="ISO 4217 currency code.", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("VOIDED", "Voided"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=15,
                    ),
                ),
                (
                    "capture_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal capture ID returned after a successful capture.",
                        max_length=64,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Full PayPal API response stored for audit/debugging.",
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"role": "vendor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paypal_orders",
                        to="subscriptions.vendorsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Order",
                "verbose_name_plural": "PayPal Orders",
                "db_table": "paypal_order",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "status"],
                        name="idx_paypal_order_vendor_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayPalSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "paypal_sub_id",
                    models.CharField(
                        db_index=True,
                        help_text="PayPal subscription ID (e.g. I-XXXXXXXXX).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "paypal_plan_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal billing plan ID this subscription is linked to.",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPROVAL_PENDING", "Approval Pending"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="APPROVAL_PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "next_billing_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next scheduled billing date from PayPal.",
                        null=True,
                    ),
                ),
                (
                    "last_payment_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_payment_time", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="Latest PayPal subscription object for audit/debugging.",
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        limit_choices_to={"role": "vendor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paypal_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor_subscription",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paypal_subscription",
                        to="subscriptions.vendorsubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Subscription",
                "verbose_name_plural": "PayPal Subscriptions",
                "db_table": "paypal_subscription",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vendor", "status"], name="idx_paypal_sub_vendor_status"
                    )
                ],
            },
        ),
    ]
