# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "serial_number",
                    models.CharField(
                        db_index=True,
                        help_text="Hardware serial number printed on the device.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("revoked", "Revoked"),
                            ("retired", "Retired"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=15,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Scanner",
                "verbose_name_plural": "Scanners",
                "db_table": "scanner",
                "ordering": ["serial_number"],
            },
        ),
    ]
