# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scanners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scanner",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_scanners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scanner",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={"role": "vendor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="scanner",
            index=models.Index(
                condition=models.Q(("status", "available")),
                fields=["status"],
                name="idx_scanner_status_available",
            ),
        ),
    ]
