# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("sales", "0001_initial"),
        ("storekeeper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="storekeeper.cart",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="products.product",
            ),
        ),
    ]
