# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["vendor", "sold_at"], name="idx_sale_vendor_sold_at"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["vendor", "product"], name="idx_sale_vendor_product"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["vendor", "payment_method"], name="idx_sale_vendor_payment"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["product", "sold_at"], name="idx_sale_product_sold_at"
            ),
        ),
    ]
