# Generated by Django 6.0.3 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="sale",
            name="unit",
            field=models.CharField(
                default="each",
                help_text="Snapshotted from product at sale time.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Supports fractional units for weighed items (e.g. 2.500 kg).",
                max_digits=10,
            ),
        ),
    ]
