# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "business_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, unique=True
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("retail", "Retail"),
                            ("wholesale", "Wholesale"),
                            ("pharmacy", "Pharmacy"),
                            ("supermarket", "Supermarket"),
                            ("electronics", "Electronics"),
                            ("fashion", "Fashion"),
                            ("food_bev", "Food & Beverage"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("business_description", models.TextField(blank=True, max_length=300)),
                (
                    "business_logo",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL — set via media upload endpoint.",
                    ),
                ),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("city_town", models.CharField(blank=True, max_length=100)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                ("nearest_landmark", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="ISO 4217 code. Defaults to NGN.",
                        max_length=3,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="geography.country",
                    ),
                ),
                (
                    "lga",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="geography.lga",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="geography.state",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Profile",
                "verbose_name_plural": "Vendor Profiles",
                "db_table": "vendor_profile",
                "indexes": [
                    models.Index(fields=["state", "lga"], name="idx_vendor_state_lga"),
                    models.Index(
                        fields=["state", "business_type"], name="idx_vendor_state_type"
                    ),
                ],
            },
        ),
    ]
