# Generated by Django 6.0.3 on 2026-03-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorprofile",
            name="business_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Platform-wide unique business name. NULL until the vendor sets it in Settings.",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
