# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["vendor", "status"], name="idx_report_vendor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "created_at"], name="idx_report_status_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("vendor", "report_type", "period_start"),
                name="uq_report_vendor_type_period",
            ),
        ),
    ]
