"""
apps/reports/models.py
======================
Stores metadata for each generated PDF report.
The PDF is generated by a Celery task, uploaded to Cloudinary
and the URL saved here. Vendors download past reports without
regenerating them.

Index strategy:
  - vendor + report_type + period_start: unique constraint
    (no duplicate reports for same vendor + type + period)
  - vendor + status: composite (list ready reports for vendor)
  - status + created_at: composite (admin: find failed reports)
"""

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.models import TimeStampedModel


class Report(TimeStampedModel):

    class ReportType(models.TextChoices):
        WEEKLY  = "weekly",  _("Weekly")
        MONTHLY = "monthly", _("Monthly")

    class Status(models.TextChoices):
        PENDING    = "pending",    _("Pending")
        GENERATING = "generating", _("Generating")
        READY      = "ready",      _("Ready")
        FAILED     = "failed",     _("Failed")

    vendor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="reports",
        db_index=True,
        limit_choices_to={"role": "vendor"},
    )
    report_type  = models.CharField(
        max_length=10,
        choices=ReportType.choices,
        db_index=True,
    )
    period_start = models.DateField()
    period_end   = models.DateField()
    status       = models.CharField(
        max_length=15,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )
    file_url     = models.URLField(blank=True)
    file_size_kb = models.PositiveIntegerField(default=0)
    generated_at = models.DateTimeField(null=True, blank=True)
    error_detail = models.TextField(blank=True)

    class Meta:
        db_table            = "report"
        verbose_name        = _("Report")
        verbose_name_plural = _("Reports")
        ordering            = ["-created_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["vendor", "report_type", "period_start"],
                name="uq_report_vendor_type_period",
            ),
        ]
        indexes = [
            models.Index(
                fields=["vendor", "status"],
                name="idx_report_vendor_status",
            ),
            models.Index(
                fields=["status", "created_at"],
                name="idx_report_status_created",
            ),
        ]

    def __str__(self) -> str:
        return (
            f"{self.get_report_type_display()} — "
            f"{self.vendor.email} "
            f"[{self.period_start} → {self.period_end}]"
        )