# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "product_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("brand", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("each", "Each"),
                            ("carton", "Carton"),
                            ("kg", "Kilogram"),
                            ("litre", "Litre"),
                            ("pack", "Pack"),
                            ("dozen", "Dozen"),
                            ("bag", "Bag"),
                            ("box", "Box"),
                        ],
                        default="each",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL — set by process_new_product task.",
                    ),
                ),
                ("sku", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="System-generated Code128 barcode string.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "barcode_image",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary URL for the rendered barcode PNG.",
                    ),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "discount_expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("total_sold", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ["-created_at"],
            },
        ),
    ]
