# Generated by Django 6.0.3 on 2026-03-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode_image",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Cloudinary URL for the rendered barcode PNG.",
                null=True,
            ),
        ),
    ]
