# Generated by Django 6.0.3 on 2026-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_barcode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="System-generated Code128 barcode string.",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode_image",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="Cloudinary URL for the rendered barcode PNG.",
            ),
        ),
    ]
