# Generated by Django 6.0.3 on 2026-03-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_barcode_alter_product_barcode_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode_image",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cloudinary URL for the rendered barcode PNG.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cloudinary URL — set by process_new_product task.",
            ),
        ),
    ]
