# Generated by Django 6.0.3 on 2026-03-21 23:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_barcode_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default=None,
                help_text="Product image — uploaded directly to Cloudinary.",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
    ]
