# Generated by Django 6.0.3 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_brand_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_variable_quantity",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If True, the cashier enters the measured quantity at sale time (e.g. weight in kg). selling_price is treated as price-per-unit.",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="minimum_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Minimum sellable quantity for variable-quantity products (e.g. 0.5 kg). Leave blank for no minimum.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity_in_stock",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
