# Generated by Django 6.0.3 on 2026-04-09 23:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("restore", "Restored"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                            ("password_changed", "Changed Password"),
                            ("profile_updated", "Updated Profile"),
                            ("product_uploaded", "Uploaded Product"),
                            ("product_approved", "Approved Product"),
                            ("product_rejected", "Rejected Product"),
                            ("stock_updated", "Updated Stock"),
                            ("order_created", "Created Order"),
                            ("order_confirmed", "Confirmed Order"),
                            ("order_shipped", "Shipped Order"),
                            ("order_delivered", "Delivered Order"),
                            ("order_cancelled", "Cancelled Order"),
                            ("refund_requested", "Requested Refund"),
                            ("refund_approved", "Approved Refund"),
                            ("subscription_created", "Created Subscription"),
                            ("subscription_upgraded", "Upgraded Subscription"),
                            ("subscription_downgraded", "Downgraded Subscription"),
                            ("subscription_cancelled", "Cancelled Subscription"),
                            ("subscription_renewed", "Renewed Subscription"),
                            ("payment_processed", "Processed Payment"),
                            ("payment_failed", "Failed Payment"),
                            ("payment_refunded", "Refunded Payment"),
                            ("user_approved", "Approved User"),
                            ("user_rejected", "Rejected User"),
                            ("user_suspended", "Suspended User"),
                            ("user_unsuspended", "Unsuspended User"),
                            ("report_generated", "Generated Report"),
                            ("export_created", "Created Export"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of the activity",
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data related to the activity",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="activity_lo_user_id_f9dfaa_idx",
                    ),
                    models.Index(
                        fields=["action_type"], name="activity_lo_action__d21993_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="activity_lo_created_8906e2_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activity_lo_content_c82b76_idx",
                    ),
                ],
            },
        ),
    ]
