# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("account_approved", "Account Approved"),
                            ("account_rejected", "Account Rejected"),
                            ("account_suspended", "Account Suspended"),
                            ("subscription_activated", "Subscription Activated"),
                            ("subscription_renewal", "Subscription Renewal Reminder"),
                            ("subscription_expired", "Subscription Expired"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("plan_upgraded", "Plan Upgraded"),
                            ("plan_downgrade_scheduled", "Plan Downgrade Scheduled"),
                            ("product_ready", "Product Ready"),
                            ("product_failed", "Product Processing Failed"),
                            ("low_stock", "Low Stock Alert"),
                            ("daily_summary", "Daily Sales Summary"),
                            ("new_vendor", "New Vendor Application"),
                            ("system", "System Message"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "In-App Only"),
                            ("email", "Email Only"),
                            ("both", "In-App and Email"),
                        ],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "related_object_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("action_url", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
