# Generated by Django 6.0.3 on 2026-03-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storekeeper", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="uq_cart_item_cart_product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="unit",
            field=models.CharField(default="each", max_length=10),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
