# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingPlanChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "new_billing_cycle",
                    models.CharField(
                        blank=True,
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        max_length=10,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("downgrade", "Downgrade"),
                            ("cycle_change", "Billing Cycle Change"),
                            ("cancellation", "Cancellation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "change_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("effective_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Pending Plan Change",
                "verbose_name_plural": "Pending Plan Changes",
                "db_table": "pending_plan_change",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        db_index=True,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "product_limit",
                    models.PositiveIntegerField(
                        help_text="Max active products. 0 = unlimited."
                    ),
                ),
                (
                    "monthly_price_ngn",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "yearly_price_ngn",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("has_analytics", models.BooleanField(default=False)),
                ("has_reports", models.BooleanField(default=False)),
                ("has_multi_branch", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "subscription_plan",
                "ordering": ["monthly_price_ngn"],
            },
        ),
        migrations.CreateModel(
            name="VendorSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("NGN", "Nigerian Naira"),
                            ("USD", "US Dollar"),
                            ("GBP", "British Pound"),
                        ],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Admin Approval"),
                            ("pending_payment", "Pending Payment"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "stripe_sub_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe subscription ID for recurring billing.",
                        max_length=255,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Vendor Subscription",
                "verbose_name_plural": "Vendor Subscriptions",
                "db_table": "vendor_subscription",
                "ordering": ["-created_at"],
            },
        ),
    ]
