# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingplanchange",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_plan_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pendingplanchange",
            name="new_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_changes",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="vendorsubscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="vendorsubscription",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"role": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="pendingplanchange",
            index=models.Index(
                fields=["change_status", "effective_at"],
                name="idx_pending_change_status_date",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingplanchange",
            index=models.Index(
                fields=["vendor", "change_status"], name="idx_pending_change_vendor"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorsubscription",
            index=models.Index(
                fields=["vendor", "status"], name="idx_sub_vendor_status"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorsubscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="idx_sub_status_period_end",
            ),
        ),
    ]
