# Generated by Django 6.0.3 on 2026-03-26 12:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Activation"),
                            ("renewal", "Renewal"),
                            ("upgrade", "Plan Upgrade (Prorated)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "stripe_intent_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_records",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="subscriptions.vendorsubscription",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Record",
                "verbose_name_plural": "Payment Records",
                "db_table": "subscription_payment_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["plan", "created_at"], name="idx_pr_plan_date"
                    ),
                    models.Index(
                        fields=["vendor", "created_at"], name="idx_pr_vendor_date"
                    ),
                ],
            },
        ),
    ]
