# Generated by Django 6.0.3 on 2026-04-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_paymentrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorsubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Customer ID (cus_xxxxx) for recurring billing.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vendorsubscription",
            name="stripe_payment_method_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentMethod ID (pm_xxxxx) for auto-renewal.",
                max_length=255,
            ),
        ),
    ]
