# Generated by Django 6.0.3 on 2026-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_vendorsubscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorsubscription",
            name="stripe_sub_id",
        ),
        migrations.AddField(
            model_name="vendorsubscription",
            name="stripe_last_intent_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe PaymentIntent ID (pi_xxxxx) from the most recent successful charge. Not a Stripe Subscription ID — billing is managed manually via Celery Beat + PaymentIntents.",
                max_length=255,
            ),
        ),
    ]
