# Generated by Django 6.0.3 on 2026-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_remove_vendorsubscription_stripe_sub_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={
                "ordering": ["monthly_price_gbp"],
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
            },
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="monthly_price_ngn",
            new_name="monthly_price_gbp",
        ),
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="yearly_price_ngn",
            new_name="yearly_price_gbp",
        ),
        migrations.AlterField(
            model_name="paymentrecord",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
        migrations.AlterField(
            model_name="vendorsubscription",
            name="currency",
            field=models.CharField(
                choices=[("GBP", "British Pound")], default="GBP", max_length=3
            ),
        ),
    ]
