# Generated by Django 6.0.3 on 2026-03-19 23:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 3166-1 alpha-2 code e.g. NG, GB, GH.",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        default="NGN",
                        help_text="ISO 4217 currency code e.g. NGN, GBP, USD.",
                        max_length=3,
                    ),
                ),
                ("currency_symbol", models.CharField(default="₦", max_length=5)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "geo_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="State abbreviation e.g. OY, LA, AB.", max_length=10
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="geography.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
                "db_table": "geo_state",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LGA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lgas",
                        to="geography.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "LGA",
                "verbose_name_plural": "LGAs",
                "db_table": "geo_lga",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="state",
            index=models.Index(
                fields=["country", "name"], name="idx_state_country_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="uq_state_country_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                fields=("country", "name"), name="uq_state_country_name"
            ),
        ),
        migrations.AddIndex(
            model_name="lga",
            index=models.Index(fields=["state", "name"], name="idx_lga_state_name"),
        ),
        migrations.AddConstraint(
            model_name="lga",
            constraint=models.UniqueConstraint(
                fields=("state", "name"), name="uq_lga_state_name"
            ),
        ),
    ]
